### ISSUE TITLE
关于 ID 的 Sequence 的问题

### ISSUE THREAD

**Issue by ghost** [alifiroozi80/duckdb#1]
在迁移文件 migrator.go 的 CreateTable 方法里面，有一段代码：

```
if dbName == "id" {
  s := "{products  %!s(bool=false)}"
  re := regexp.MustCompile(`\{([^ ]+)`)
  match := re.FindStringSubmatch(s)
  pk := fmt.Sprintf("? ? DEFAULT nextval('%s')", match[1])
  createTableSQL += pk

} else {
  createTableSQL += "? ?"
}
```

为什么是 `s := "{products  %!s(bool=false)}"` 呢？
为什么不使用 `m.createSequence` 方法生成的 Sequence 呢？

另外，为什么只有 id 才会使用 Sequence？如果存在其它自增字段，该怎么写？

**Comment by alifiroozi80** [comment]
Hello @zestack 

> Why not use the Sequence generated by the m.createSequence method?

Nice catch!
Fixed at [#2](https://github.com/alifiroozi80/duckdb/pull/2)

> In addition, why is Sequence used only for ID? If there are other auto-increment fields, how should they be written?

That's another valid point!

But there are a couple of matters first to consider:

* The `sequence` in DuckDB is the implementation of `AUTO_INCREMENT` in other SQL DBs (like Postgres.)
* This field is usually used with `ID` (To create primary indexes)
* I used the `m.createSequence` method to create this sequence for the ID. If you want to use the same sequence for other fields, the sequence numbers would be corrupt for ID (See below)

```duckdb
v1.1.2 f680b7d08f
Enter ".help" for usage hints.
D CREATE TABLE Persons (
      Personid integer primary key,
      LastName varchar(255) not null,
      xxx integer primary key
  );
Parser Error: table "Persons" has more than one primary key
D CREATE TABLE Persons (
      Personid integer primary key,
      LastName varchar(255) not null,
      xxx integer
  );
D SELECT * FROM Persons;
┌──────────┬──────────┬───────┐
│ Personid │ LastName │  xxx  │
│  int32   │ varchar  │ int32 │
├──────────┴──────────┴───────┤
│           0 rows            │
└─────────────────────────────┘
D CREATE SEQUENCE seq_personid START 1;
D INSERT INTO Persons VALUES (nextval('seq_personid'), 'Doe', 90);
D SELECT * FROM Persons;
┌──────────┬──────────┬───────┐
│ Personid │ LastName │  xxx  │
│  int32   │ varchar  │ int32 │
├──────────┼──────────┼───────┤
│        1 │ Doe      │    90 │
└──────────┴──────────┴───────┘
D INSERT INTO Persons VALUES (nextval('seq_personid'), 'Doe', nextval('seq_personid'));
D SELECT * FROM Persons;
┌──────────┬──────────┬───────┐
│ Personid │ LastName │  xxx  │
│  int32   │ varchar  │ int32 │
├──────────┼──────────┼───────┤
│        1 │ Doe      │    90 │
│        2 │ Doe      │     3 │
└──────────┴──────────┴───────┘
D
D INSERT INTO Persons VALUES (nextval('seq_personid'), 'Doe', 99);
D SELECT * FROM Persons;
┌──────────┬──────────┬───────┐
│ Personid │ LastName │  xxx  │
│  int32   │ varchar  │ int32 │
├──────────┼──────────┼───────┤
│        1 │ Doe      │    90 │
│        2 │ Doe      │     3 │
│        4 │ Doe      │    99 │
└──────────┴──────────┴───────┘
```

You see that ID now is corrupt.

Unless, for each field that needs sequence, create a new sequence. If this is your point and your feature request, either you'll have to implement it and contribute (Contributions are greatly appreciated!) or wait for me (or others) to implement this [I will add this to [Roadmap](https://github.com/alifiroozi80/duckdb?tab=readme-ov-file#roadmap) for you or other contributors].

Let me know.

Cheers🍻
